user:
    0000-0002-2907-313:
        name: Melodee Helene Beals
        affiliation: 
        gravatarhash: 82b4d22865fcd47198ac2bd283b3f08e

articles:
    10.6084/M9.FIGSHARE.944593:
        title: The Role of the Sydney Gazette in the Creation of Australia in the Scottish Public Sphere
        doi: 10.6084/M9.FIGSHARE.944593
        summary: Building upon my postgraduate research, I turned to a deeper analysis of Scottish journalism, namely the representations of colonial Australia in the early years of the nineteenth century. This article represents my first work on Scissors-and-Paste journalism.
        image: https://c2.staticflickr.com/8/7503/15795863409_f8a8bd3bd9_z.jpg
    10.1080/13555502.2013.865977:
        title: "Rapunzel and the Ivory Tower: How Open Access Will Save the Humanities (from Themselves)"
        doi: 10.1080/13555502.2013.865977
        summary: As I developed as a writer and researcher, I found myself increasingly concerned with the current publication ecosystem. This article, one of a four-part collection on open access within the humanities, consolidated my views on the ethical and practical impetus to move toward new publication models.
        image: https://c2.staticflickr.com/6/5612/15567560315_fa15117bcc.jpg
